"""users table

Revision ID: cfc458aad86e
Revises: 
Create Date: 2024-10-13 18:23:34.381322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc458aad86e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_db_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_db_user_username'))

    op.drop_table('db_user')
    # ### end Alembic commands ###
